ARDUINO_QUIET = 1

# base configuration
BOARD_TAG    = nano328
ARDUINO_LIBS = FastLED

# defaults
PORT   = 0

MONITOR_PORT = /dev/ttyUSB$(PORT)
OBJDIR       = build-$(BOARD_TAG)

include /usr/share/arduino/Arduino.mk
