#!/bin/sh
cd $(dirname "$(readlink -f "$0")")

chip="UCS1903B"

for layout in *.txt; do
    lay="$(echo $layout | cut -d. -f1)"
    fol="output/${lay}"
    fn="${fol}/layout.h"
    mkdir -p $fol

    echo "// generated layout" > $fn
    echo "\n#define BOARD_LAYOUT 0x${lay}\n" >> $fn
    echo "void configure(struct CRGB *leds) {" >> $fn

    ofs=0
    pin=4
    for len in $(cat $layout); do
        echo "    FastLED.addLeds<${chip}, ${pin}>(leds, ${ofs}, ${len});"
        ofs=$(expr $ofs + $len)
        pin=$(expr $pin + 1)
    done >> $fn
    echo "}" >> $fn
    echo "\n#define LED_LENGTH ${ofs}" >> $fn

    echo "  generated layout ${lay} (strips: $(wc -l < $layout))"
done
